#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: duckdb/duckdb/.github/workflows/_extension_distribution.yml@0e784765f6f87bd1ce9034afcce1e7f89fcd8777
    with:
      vcpkg_commit: a42af01b72c28a8e1d7b48107b33e4f286a55ef6
      duckdb_version: 0e784765f6
      extension_name: sqlite_scanner
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: duckdb/duckdb/.github/workflows/_extension_deploy.yml@0e784765f6f87bd1ce9034afcce1e7f89fcd8777
    secrets: inherit
    with:
      duckdb_version: 0e784765f6
      extension_name: sqlite_scanner
      exclude_archs: 'wasm_mvp;wasm_eh;wasm_threads'
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
      deploy_versioned: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}
